#! /bin/bash

# fix the paths in the dylibs for macOS
if [[ "$OSTYPE" == "darwin"* ]]; then
install_name_tool -change libtwh5.dylib @loader_path/libtwh5.dylib ${R_PACKAGE_DIR}/libs/TofDaqR.so
install_name_tool -change libtwtool.dylib @loader_path/libtwtool.dylib ${R_PACKAGE_DIR}/libs/TofDaqR.so
install_name_tool -change libtwtool.dylib @loader_path/libtwtool.dylib ${R_PACKAGE_DIR}/libs/libtwh5.dylib
fi

# restore RcppExport.cpp
mv ./src/RcppExports.cpp.windows ./src/RcppExports.cpp
rm ./src/RcppExports.cpp.tmp

# restore zzz.R
mv ./R/zzz.R.windows ./R/zzz.R

# move TofDaqDll help files back to ./man
mv ./tools/*.Rd ./man
