#! /bin/bash

# restore TofDaqDll.R and original NAMESPACE, ./man and zzz.R
if [ -e ./tools/TofDaqDll.R ]; then
mv ./tools/TofDaqDll.R ./R/TofDaqDll.R
fi
if [ -e ./tools/AdditionalTofDaqDll.R ]; then
mv ./tools/AdditionalTofDaqDll.R ./R/AdditionalTofDaqDll.R
fi
if [ -e ./tools/NAMESPACE.windows ]; then
mv ./tools/NAMESPACE.windows NAMESPACE
fi
if [ -e ./tools/man.windows/ ]; then
mv ./tools/man.windows/* ./man
rm -r ./tools/man.windows
fi
if [ -e ./tools/zzz.R.windows ]; then
mv ./tools/zzz.R.windows ./R/zzz.R
fi

# fix the paths in the dylibs for macOS
if [[ "$OSTYPE" == "darwin"* && -e "${R_PACKAGE_DIR}/libs" ]]; then
cd "${R_PACKAGE_DIR}/libs"
install_name_tool -change libtwh5.dylib @loader_path/libtwh5.dylib TofDaqR.so
install_name_tool -change libtwtool.dylib @loader_path/libtwtool.dylib TofDaqR.so
install_name_tool -change libtwtool.dylib @loader_path/libtwtool.dylib libtwh5.dylib
fi
