// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DecodeEventList
List DecodeEventList(NumericVector events, double clockPeriod, double sampleInterval);
RcppExport SEXP TofDaqR_DecodeEventList(SEXP eventsSEXP, SEXP clockPeriodSEXP, SEXP sampleIntervalSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type events(eventsSEXP);
    Rcpp::traits::input_parameter< double >::type clockPeriod(clockPeriodSEXP);
    Rcpp::traits::input_parameter< double >::type sampleInterval(sampleIntervalSEXP);
    __result = Rcpp::wrap(DecodeEventList(events, clockPeriod, sampleInterval));
    return __result;
END_RCPP
}
// EventList2TofSpec
NumericVector EventList2TofSpec(NumericVector events, double clockPeriod, double sampleInterval, double nbrSamples);
RcppExport SEXP TofDaqR_EventList2TofSpec(SEXP eventsSEXP, SEXP clockPeriodSEXP, SEXP sampleIntervalSEXP, SEXP nbrSamplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type events(eventsSEXP);
    Rcpp::traits::input_parameter< double >::type clockPeriod(clockPeriodSEXP);
    Rcpp::traits::input_parameter< double >::type sampleInterval(sampleIntervalSEXP);
    Rcpp::traits::input_parameter< double >::type nbrSamples(nbrSamplesSEXP);
    __result = Rcpp::wrap(EventList2TofSpec(events, clockPeriod, sampleInterval, nbrSamples));
    return __result;
END_RCPP
}
