#! /bin/bash

# run this script once after updating the TofDaq API files.
# Note: make sure this file is saved with Unix line endings (LF).

# add ChangeIonMode (which does not exist by default) to TofDaqDll.h
if !(grep -Fq ionMode ./include/TofDaqDll.h) ; then
sed -i.bak '/keepOpen/ a\
////////////////////////////////////////////////////////////////////////////////\
TOFWERK_DAQ_API TwRetVal TwTpsChangeIonMode(int ionMode);' ./include/TofDaqDll.h
rm ./include/TofDaqDll.h.bak
fi

# remove unnecessary jquery.php and js.php from /tools/doc/
if [ -f ./doc/TofDaqDll_files/jquery.php ] ; then
  rm ./doc/TofDaqDll_files/jquery.php
  rm ./doc/TofDaqDll_files/js.php
  rm ./doc/TofwerkHDF5_files/jquery.php
  rm ./doc/TofwerkHDF5_files/js.php
  rm ./doc/TwH5Dll_files/jquery.php
  rm ./doc/TwH5Dll_files/js.php
  rm ./doc/TwToolDll_files/jquery.php
  rm ./doc/TwToolDll_files/js.php
fi
