#! /bin/bash

# run this script once after updating the TofDaq API files.

# add ChangeIonMode (which does not exist by default) to TofDaqDll.h
if !(grep -Fq ionMode ./include/TofDaqDll.h) ; then
sed -i.bak '/keepOpen/ a\
////////////////////////////////////////////////////////////////////////////////\
TOFWERK_DAQ_API TwRetVal TwTpsChangeIonMode(int ionMode);' ./include/TofDaqDll.h
rm ./include/TofDaqDll.h.bak
fi

# remove unnecessary jquery.php from /inst/doc/
if [ -f ../inst/doc/TofDaqDll_files/jquery.php ] ; then
  rm ../inst/doc/TofDaqDll_files/jquery.php
  rm ../inst/doc/TofwerkHDF5_files/jquery.php
  rm ../inst/doc/TwH5Dll_files/jquery.php
  rm ../inst/doc/TwToolDll_files/jquery.php
fi
