# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Decodes an event list.
#'
#' \code{DecodeEventList} decodes an event list read with \code{GetEventList...FromH5}
#' functions into a time stamp vector and a data vector.
#'
#' Note: this function is not part of the TofDaq API, but is included in the
#' package for convenience.
#'
#' @param events Event data, e.g. from \code{GetEventList...FromH5}.
#' @param clockPeriod Clock period in ns, e.g. from
#' \code{GetFloatAttributeFromH5(filename, "FullSpectra", "ClockPeriod")}.
#' @param sampleInterval Sampling interval in ns, e.g. from \code{\link{GetH5Descriptor}}.
#' @return A list with sample indices and data values (in mV).
#' @export
DecodeEventList <- function(events, clockPeriod, sampleInterval) {
    .Call('TofDaqR_DecodeEventList', PACKAGE = 'TofDaqR', events, clockPeriod, sampleInterval)
}

#' Converts events of an event list into a spectrum.
#'
#' \code{EventList2TofSpec} converts events of an event list (read with
#' \code{GetEventList...FromH5} functions) into a spectrum.
#'
#' Note: this function is not part of the TofDaq API, but is included in the
#' package for convenience.
#'
#' @param events Event data, e.g. from \code{GetEventList...FromH5}.
#' @param clockPeriod Clock period in ns, e.g. from
#' \code{GetFloatAttributeFromH5(filename, "FullSpectra", "ClockPeriod")}.
#' @param sampleInterval Sampling interval in ns, e.g. from \code{\link{GetH5Descriptor}}.
#' @param nbrSamples Number of samples, e.g. from \code{\link{GetH5Descriptor}}.
#' @return A vector containing the spectrum.
#' @export
EventList2TofSpec <- function(events, clockPeriod, sampleInterval, nbrSamples) {
    .Call('TofDaqR_EventList2TofSpec', PACKAGE = 'TofDaqR', events, clockPeriod, sampleInterval, nbrSamples)
}

